# Site settings
title: Perpetual Twiddler
description: > # this means to ignore newlines until "baseurl:"
  Notes for reference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://perpetualtwiddler.github.io" # the base hostname & protocol for your site
github_username:  perpetualtwiddler

# Build settings
markdown: kramdown
